# Generated by Django 5.2.17 on 2026-10-03 22:12

import django.db.models.deletion
import questions.models
import questions.private_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='DocxImportSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preview', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parsed_id', models.CharField(max_length=40)),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('file', models.FileField(storage=questions.private_storage.QuestionPrivateStorage(), upload_to=questions.models.question_media_path)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='questions.docximportsession')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='questions.question')),
            ],
            options={
                'ordering': ('order', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('import_session__isnull', True), ('question__isnull', False)), models.Q(('import_session__isnull', False), ('question__isnull', True)), _connector='OR'), name='question_media_single_owner')],
            },
        ),
    ]
