# Generated by Django 5.2.17 on 2026-10-04 04:03

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_source_metadata_docximportsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmedia',
            name='import_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=questions.models.cascade_private_media, related_name='media', to='questions.docximportsession'),
        ),
        migrations.AlterField(
            model_name='questionmedia',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=questions.models.cascade_private_media, related_name='media', to='questions.question'),
        ),
    ]
