# Generated by Django 5.2.17 on 2026-09-29 22:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_remove_groupmembership_unique_active_group_membership_and_more'),
        ('institutions', '0001_initial'),
        ('questions', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('class_test', 'Class test'), ('continuous_assessment', 'Continuous assessment'), ('test', 'Test'), ('mock_exam', 'Mock exam'), ('term_exam', 'Term exam'), ('entrance_exam', 'Entrance exam'), ('placement_test', 'Placement test'), ('competition', 'Competition'), ('certification_exam', 'Certification exam'), ('training_assessment', 'Training assessment')], max_length=32)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('pass_mark', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_limit', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('randomize_questions', models.BooleanField(default=False)),
                ('randomize_options', models.BooleanField(default=False)),
                ('security_level', models.CharField(choices=[('standard', 'Standard'), ('enhanced', 'Enhanced')], default='standard', max_length=16)),
                ('result_visibility', models.CharField(choices=[('hidden', 'Hidden'), ('after_submission', 'After submission'), ('scheduled_release', 'Scheduled release')], default='hidden', max_length=24)),
                ('candidate_access', models.CharField(choices=[('assigned_group', 'Assigned group'), ('specific_candidates', 'Specific candidates'), ('access_code', 'Access code')], default='assigned_group', max_length=24)),
                ('review_allowed', models.BooleanField(default=False)),
                ('result_release_mode', models.CharField(choices=[('immediate', 'Immediate'), ('approval_required', 'Approval required'), ('manual_release', 'Manual release')], default='approval_required', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assessments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='groups.group')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='institutions.institution')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='subjects.subject')),
            ],
            options={
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('marks', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.assessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_links', to='questions.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['institution', 'status'], name='assessment_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['institution', 'subject'], name='assessment_tenant_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['institution', 'group'], name='assessment_tenant_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'question'), name='unique_question_per_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='unique_assessment_question_order'),
        ),
    ]
