# Generated by Django 5.2.17 on 2026-09-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='resume_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
