# Generated by Django 5.2.17 on 2026-10-03 11:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_resume_allowed'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickExamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_configuration', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='QuickExamCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_credentials', to='candidates.candidate')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='assessments.quickexamconfiguration')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_quick_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuickExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_digest', models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Store a SHA-256 token digest only.')])),
                ('credential_version', models.PositiveIntegerField()),
                ('configuration_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessments.quickexamcredential')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quickexamconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('session_version__gte', 1)), name='quick_config_version_positive'),
        ),
        migrations.AddIndex(
            model_name='quickexamcredential',
            index=models.Index(fields=['configuration', 'active'], name='quick_credential_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='quickexamcredential',
            constraint=models.UniqueConstraint(fields=('configuration', 'candidate'), name='unique_quick_candidate_cred'),
        ),
        migrations.AddConstraint(
            model_name='quickexamcredential',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='quick_credential_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='quickexamsession',
            constraint=models.CheckConstraint(condition=models.Q(('credential_version__gte', 1)), name='quick_session_cred_version_pos'),
        ),
        migrations.AddConstraint(
            model_name='quickexamsession',
            constraint=models.CheckConstraint(condition=models.Q(('configuration_version__gte', 1)), name='quick_session_config_ver_pos'),
        ),
    ]
