# Generated by Django 5.2.5 on 2026-09-29 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='institutionmembership',
            name='unique_active_institution_membership',
        ),
        migrations.AddConstraint(
            model_name='institutionmembership',
            constraint=models.UniqueConstraint(fields=('user', 'institution'), name='unique_user_institution_membership'),
        ),
    ]
