export const candidateCopy = {
  'Delete candidate': 'حذف المرشح', 'Delete candidate?': 'حذف المرشح؟',
  'You are about to permanently delete:': 'أنت على وشك حذف المرشح التالي نهائيا:',
  'This action cannot be undone.': 'لا يمكن التراجع عن هذا الإجراء.',
  'The linked user account will remain.': 'سيبقى حساب المستخدم المرتبط محفوظا.',
  'This candidate has assessment history and cannot be permanently deleted. Deactivate the candidate instead.': 'لدى هذا المرشح سجل اختبارات، ولذلك لا يمكن حذفه نهائيا. يمكنك تعطيل المرشح بدلا من ذلك.',
  'Deleting…': 'جار الحذف…',
  'Check this value.': 'راجع هذه القيمة.',
  Candidates: 'المرشحون', 'Add candidate': 'إضافة مرشح', 'Candidate details': 'بيانات المرشح',
  'Manage the people taking your assessments.': 'إدارة المشاركين في تقييماتك.',
  'No candidates yet': 'لا يوجد مرشحون بعد',
  'Add your first candidate. An email, account or group is not required.': 'أضف أول مرشح. لا يلزم بريد إلكتروني أو حساب أو مجموعة.',
  'No matching candidates': 'لا توجد نتائج مطابقة', 'Try another search or status.': 'جرب بحثا أو حالة أخرى.',
  'Search by name, candidate ID or email': 'البحث بالاسم أو معرف المرشح أو البريد الإلكتروني',
  Search: 'بحث', Status: 'الحالة', 'All statuses': 'جميع الحالات',
  Active: 'نشط', Inactive: 'غير نشط', Archived: 'مؤرشف',
  Name: 'الاسم', 'Candidate ID': 'معرف المرشح', 'Email address': 'البريد الإلكتروني',
  'Portal access': 'الوصول إلى البوابة', 'Portal access enabled': 'الوصول إلى البوابة مفعل',
  'Portal access not enabled': 'الوصول إلى البوابة غير مفعل',
  'Account inactive': 'الحساب غير نشط', 'Candidate inactive': 'المرشح غير نشط',
  'Edit candidate': 'تعديل بيانات المرشح', 'Save changes': 'حفظ التغييرات', Save: 'حفظ', Cancel: 'إلغاء',
  'First name': 'الاسم الأول', 'Last name': 'اسم العائلة', 'Phone number': 'رقم الهاتف',
  'Date of birth': 'تاريخ الميلاد', Optional: 'اختياري',
  'Use the identifier your organisation assigns. It must be unique within this workspace.': 'استخدم المعرف الذي تخصصه مؤسستك. يجب ألا يتكرر داخل مساحة العمل.',
  'Inactive and archived candidates cannot enter the Student Portal. Existing exam records are retained.': 'لا يمكن للمرشحين غير النشطين أو المؤرشفين دخول بوابة الطلاب. تبقى سجلات الاختبارات محفوظة.',
  'Identity is locked after an exam attempt starts.': 'لا يمكن تغيير الهوية بعد بدء محاولة اختبار.',
  'Enable portal access': 'تفعيل الوصول إلى البوابة',
  'Email-based portal access requires a saved email and an active candidate.': 'يتطلب الوصول إلى البوابة بالبريد الإلكتروني بريدا محفوظا ومرشحا نشطا.',
  'Only workspace administrators can enable portal access.': 'يمكن لمسؤولي مساحة العمل فقط تفعيل الوصول إلى البوابة.',
  'Initial access credentials': 'بيانات الدخول الأولية',
  'These credentials are shown only now. Communicate them securely to the candidate before closing. They cannot be displayed again.': 'تظهر هذه البيانات الآن فقط. انقلها إلى المرشح بطريقة آمنة قبل الإغلاق. لا يمكن عرضها مجددا.',
  'Initial password': 'كلمة المرور الأولية', 'Sign-in page': 'صفحة تسجيل الدخول',
  'Dismiss credentials': 'إغلاق بيانات الدخول',
  'First-login password change is not enforced in this phase. No email has been sent.': 'لا يلزم تغيير كلمة المرور عند أول دخول في هذه المرحلة. لم ترسل رسالة بريد إلكتروني.',
  'This account is already linked. Credentials cannot be issued again.': 'هذا الحساب مرتبط بالفعل. لا يمكن إصدار بيانات الدخول مجددا.',
  'An account with this email already exists. Linking requires a separate controlled process.': 'يوجد حساب بهذا البريد بالفعل. يتطلب ربطه إجراء منفصلا وآمنا.',
  'Account linkage cannot change after an examination attempt starts.': 'لا يمكن تغيير ربط الحساب بعد بدء محاولة اختبار.',
  'We could not load candidates. Try again.': 'تعذر تحميل المرشحين. حاول مجددا.',
  'We could not complete this request. Please try again.': 'تعذر إكمال الطلب. يرجى المحاولة مجددا.',
  'Please check the highlighted fields.': 'يرجى مراجعة الحقول المحددة.',
  'Check this value. Candidate IDs must be unique within the workspace.': 'راجع هذه القيمة. يجب ألا يتكرر معرف المرشح داخل مساحة العمل.',
  'Try again': 'إعادة المحاولة', 'Loading candidates…': 'جار تحميل المرشحين…',
  'Select a candidate to view details.': 'اختر مرشحا لعرض بياناته.',
  'Back to candidates': 'العودة إلى المرشحين', Previous: 'السابق', Next: 'التالي',
  Page: 'الصفحة', of: 'من', 'matching candidates': 'مرشحون مطابقون',
  'Saving…': 'جار الحفظ…', 'Enabling portal access…': 'جار تفعيل الوصول إلى البوابة…',
  'Close dialog': 'إغلاق النافذة', 'Not provided': 'غير متوفر',
}
