export const examCopy = {
  'A credential already exists. Use Reset PIN to issue a new PIN.': 'توجد بيانات دخول بالفعل. استخدم إعادة إصدار رمز الدخول للحصول على رمز جديد.',
  'Leave blank for no expiry.': 'اترك الحقل فارغًا لعدم تحديد انتهاء الصلاحية.',
  'Exams': 'الاختبارات', 'Exam': 'الاختبار', 'Create Exam': 'إنشاء اختبار', 'Edit Exam': 'تعديل الاختبار',
  'Manage examinations in this workspace.': 'إدارة الاختبارات في مساحة العمل هذه.',
  'Search exams': 'البحث عن اختبار', 'Search': 'بحث', 'All statuses': 'جميع الحالات',
  'No exams found': 'لا توجد اختبارات', 'Create an exam or change your filters.': 'أنشئ اختبارًا أو غيّر خيارات البحث.',
  'Loading…': 'جارٍ التحميل…', 'We could not load this information.': 'تعذّر تحميل هذه المعلومات.', 'Retry': 'إعادة المحاولة',
  'We could not complete this request. Please try again.': 'تعذّر إكمال الطلب. يرجى المحاولة مرة أخرى.',
  'Overview': 'نظرة عامة', 'Questions': 'الأسئلة', 'Candidates': 'المرشحون', 'Access': 'الوصول',
  'Exam sections': 'أقسام الاختبار', 'Back to Exams': 'العودة إلى الاختبارات', 'Preview Exam': 'معاينة الاختبار',
  'Workspace': 'مساحة العمل', 'Title': 'العنوان', 'Description': 'الوصف', 'Assessment type': 'نوع التقييم',
  'Status': 'الحالة', 'Subject': 'المادة', 'Group / Cohort': 'المجموعة / الدفعة', 'Duration': 'المدة',
  'Duration (minutes)': 'المدة بالدقائق', 'Total marks': 'الدرجة الكلية', 'Pass mark': 'درجة النجاح',
  'Start': 'البداية', 'End': 'النهاية', 'Start (local time)': 'البداية بالتوقيت المحلي', 'End (local time)': 'النهاية بالتوقيت المحلي',
  'Attempt limit': 'الحد الأقصى للمحاولات', 'Resume allowed': 'السماح باستئناف المحاولة', 'Review allowed': 'السماح بالمراجعة',
  'Randomize questions': 'ترتيب الأسئلة عشوائيًا', 'Randomize options': 'ترتيب الخيارات عشوائيًا',
  'Security level': 'مستوى الأمان', 'Candidate access': 'وصول المرشحين', 'Result visibility': 'إظهار النتائج',
  'Release policy': 'سياسة نشر النتائج', 'Quick Exam configured': 'تم إعداد الاختبار السريع',
  'Created': 'تاريخ الإنشاء', 'Updated': 'آخر تحديث', 'Yes': 'نعم', 'No': 'لا', 'Not set': 'غير محدد',
  'minutes': 'دقائق', 'marks': 'درجات', 'Marks': 'الدرجات', 'Order': 'الترتيب', 'Question': 'السؤال',
  'Correct answer': 'الإجابة الصحيحة', 'Explanation': 'الشرح', 'No questions attached': 'لم تتم إضافة أسئلة',
  'PREVIEW MODE': 'وضع المعاينة', 'No attempt is created. No timer is running.': 'لا يتم إنشاء محاولة، ولا يعمل أي مؤقت.',
  'Configured order is shown. Candidate question or option order may vary.': 'يُعرض الترتيب المُعدّ. قد يختلف ترتيب الأسئلة أو الخيارات لدى المرشحين.',
  'Close preview': 'إغلاق المعاينة', 'Select all that apply.': 'اختر جميع الإجابات المناسبة.',
  'Choose True or False.': 'اختر صحيح أو خطأ.', 'Select one answer.': 'اختر إجابة واحدة.', 'Selected': 'محدد',
  'Question navigator': 'التنقل بين الأسئلة', 'Question status legend': 'دليل حالة الأسئلة', 'Question status': 'حالة السؤال',
  'Current': 'الحالي', 'Answered': 'تمت الإجابة', 'Unanswered': 'بلا إجابة', 'Marked for review': 'محدد للمراجعة',
  'Go to question': 'الانتقال إلى السؤال', 'Answered ': 'تمت الإجابة: ', 'Unanswered ': 'بلا إجابة: ', 'Marked for review ': 'محدد للمراجعة: ',
  'current': 'الحالي', 'answered': 'تمت الإجابة', 'unanswered': 'بلا إجابة', 'marked': 'محدد للمراجعة', 'marked for review': 'محدد للمراجعة',
  'Candidate ID': 'معرّف المرشح', 'Name': 'الاسم', 'Candidate': 'المرشح', 'Window': 'فترة الإتاحة',
  'No associated candidates': 'لا يوجد مرشحون مرتبطون',
  'These candidates have associated Quick credentials. Credential validity is managed separately in Access.': 'لدى هؤلاء المرشحين بيانات دخول للاختبار السريع. تُدار صلاحيتها بشكل منفصل في قسم الوصول.',
  'Specific-candidate delivery is not implemented.': 'إتاحة الاختبار لمرشحين محددين غير مدعومة حاليًا.',
  'Active candidates with effective group membership are shown.': 'يُعرض المرشحون النشطون ذوو العضوية السارية في المجموعة.',
  'Quick Access': 'الوصول السريع', 'Quick access requires access-code delivery.': 'يتطلب الوصول السريع إتاحة الاختبار بواسطة رمز الوصول.',
  'Credential validity is separate from the exam workflow and availability window.': 'صلاحية بيانات الدخول مستقلة عن حالة الاختبار وفترة إتاحته.',
  'Exam code': 'رمز الاختبار', 'Enabled': 'مفعّل', 'Save configuration': 'حفظ الإعدادات', 'Generate credential': 'إصدار بيانات الدخول',
  'Find candidate': 'البحث عن مرشح', 'Select candidate': 'اختر مرشحًا', 'Expiry (local time)': 'انتهاء الصلاحية بالتوقيت المحلي',
  'Credentials': 'بيانات الدخول', 'No credentials issued': 'لم يتم إصدار بيانات دخول', 'Credential status': 'حالة بيانات الدخول',
  'Candidate status': 'حالة المرشح', 'Expiry': 'انتهاء الصلاحية', 'Generated': 'تاريخ الإصدار', 'Revoked': 'ملغاة',
  'Actions': 'الإجراءات', 'Version': 'الإصدار', 'Reset PIN': 'إعادة إصدار رمز الدخول', 'Revoke': 'إلغاء', 'Revoke credential': 'إلغاء بيانات الدخول',
  'One-time PIN': 'رمز الدخول — يُعرض مرة واحدة', 'PIN': 'رمز الدخول', 'Dismiss PIN': 'إغلاق رمز الدخول',
  'Communicate this PIN securely before closing. It cannot be viewed again.': 'سلّم رمز الدخول بأمان قبل الإغلاق. لن يمكن عرضه مرة أخرى.',
  'Reset invalidates the previous PIN and active sessions.': 'تؤدي إعادة الإصدار إلى إبطال رمز الدخول السابق والجلسات النشطة.',
  'Revoke prevents access and invalidates active sessions.': 'يمنع الإلغاء الدخول ويبطل الجلسات النشطة.',
  'Valid credential': 'بيانات دخول صالحة', 'Expired': 'منتهية الصلاحية', 'Candidate inactive': 'المرشح غير نشط',
  'Confirm action': 'تأكيد الإجراء', 'Confirm this workflow change?': 'هل تريد تأكيد هذا التغيير في حالة الاختبار؟',
  'Confirm': 'تأكيد', 'Cancel': 'إلغاء', 'Close dialog': 'إغلاق النافذة', 'Edit': 'تعديل',
  'submit-review': 'إرسال للمراجعة', 'request-changes': 'طلب تعديلات', 'approve': 'اعتماد', 'schedule': 'جدولة', 'reopen': 'إعادة فتح', 'archive': 'أرشفة',
  'Exam configuration': 'إعدادات الاختبار', 'Save exam': 'حفظ الاختبار', 'Attached questions': 'الأسئلة المضافة',
  'Only drafts without attempt history can be edited.': 'يمكن تعديل المسودات التي ليس لها محاولات فقط.',
  'Create the draft first, then attach approved questions.': 'أنشئ المسودة أولًا، ثم أضف الأسئلة المعتمدة.',
  'Save subject changes before attaching questions. Only approved questions in the saved subject are available.': 'احفظ تغييرات المادة قبل إضافة الأسئلة. تتاح الأسئلة المعتمدة للمادة المحفوظة فقط.',
  'Search approved questions': 'البحث في الأسئلة المعتمدة', 'Approved question': 'سؤال معتمد', 'Select question': 'اختر سؤالًا',
  'Attach question': 'إضافة سؤال', 'Update question': 'تحديث السؤال', 'Remove question': 'إزالة السؤال',
  'Remove this question from the exam?': 'هل تريد إزالة هذا السؤال من الاختبار؟',
  'Pagination': 'التنقل بين الصفحات', 'Previous': 'السابق', 'Next': 'التالي', 'Page': 'الصفحة',
  'draft': 'مسودة', 'review': 'قيد المراجعة', 'approved': 'معتمد', 'scheduled': 'مجدول', 'archived': 'مؤرشف',
  'active': 'نشط', 'inactive': 'غير نشط', 'upcoming': 'لم تبدأ الإتاحة', 'ended': 'انتهت الإتاحة', 'open': 'متاح زمنيًا',
  'assigned_group': 'المجموعة المعينة', 'access_code': 'رمز الوصول', 'specific_candidates': 'مرشحون محددون — غير مدعوم',
  'standard': 'قياسي', 'enhanced': 'معزّز', 'hidden': 'مخفية', 'after_submission': 'بعد التسليم', 'scheduled_release': 'نشر مجدول',
  'immediate': 'فوري', 'approval_required': 'يتطلب الاعتماد', 'manual_release': 'نشر يدوي',
  'multiple_choice': 'اختيار من متعدد', 'multiple_select': 'اختيار إجابات متعددة', 'true_false': 'صحيح أو خطأ',
  'easy': 'سهل', 'medium': 'متوسط', 'hard': 'صعب',
  'quiz': 'اختبار قصير', 'assignment': 'تكليف', 'class_test': 'اختبار صفي', 'continuous_assessment': 'تقييم مستمر',
  'test': 'اختبار', 'mock_exam': 'اختبار تجريبي', 'term_exam': 'اختبار فصلي', 'entrance_exam': 'اختبار قبول',
  'placement_test': 'اختبار تحديد مستوى', 'competition': 'مسابقة', 'certification_exam': 'اختبار شهادة', 'training_assessment': 'تقييم تدريبي',
}
