export const outcomesCopy = {
  'Result availability': 'إتاحة النتائج', 'When should candidates see their results?': 'متى ينبغي أن يرى المرشحون نتائجهم؟',
  'When I release them': 'عندما أنشرها', 'After they submit': 'بعد تسليم إجاباتهم', 'After the exam closes': 'بعد إغلاق الاختبار',
  'Keep results hidden': 'إبقاء النتائج مخفية', 'Release Remaining Results': 'نشر النتائج المتبقية',
  'Change Result Settings': 'تغيير إعدادات النتائج',
  'Results are kept hidden from candidates.': 'تظل النتائج مخفية عن المرشحين.',
  'Candidates can see their results only after you release them.': 'يمكن للمرشحين رؤية نتائجهم فقط بعد نشرها.',
  'Results become available when submitted attempts are marked.': 'تصبح النتائج متاحة عند تصحيح المحاولات المسلّمة.',
  'Candidates can see results only after the exam closes and you release them.': 'يمكن للمرشحين رؤية النتائج فقط بعد إغلاق الاختبار ونشرها.',
  'Candidates can see published results only after the exam closes. Results marked before closing still need to be released.': 'يمكن للمرشحين رؤية النتائج المنشورة فقط بعد إغلاق الاختبار. يجب نشر النتائج التي صُححت قبل الإغلاق أيضاً.',
  'Result settings cannot be changed after an exam attempt has started. Configure result availability on a new draft before candidates start.': 'لا يمكن تغيير إعدادات النتائج بعد بدء محاولة اختبار. اضبط إتاحة النتائج في مسودة جديدة قبل بدء المرشحين.',
  'Result settings can only be changed on a draft exam. Review the exam workflow in Overview.': 'يمكن تغيير إعدادات النتائج في مسودة اختبار فقط. راجع مسار الاختبار في صفحة الملخص.',
  'Review and manage assessment results across your institution.': 'راجع نتائج التقييمات في مؤسستك وأدرها.',
  'Generate and download assessment reports.': 'أنشئ تقارير التقييمات ونزّلها.',
  'Monitor assessment participation across your institution.': 'تابع المشاركة في تقييمات مؤسستك.',
  'Search assessments': 'البحث عن التقييمات', 'No assessments found': 'لم يتم العثور على تقييمات',
  'Assessments will appear here when they are created. Try changing your search.': 'ستظهر التقييمات هنا عند إنشائها. حاول تغيير البحث.',
  'View Results': 'عرض النتائج', 'View Report': 'عرض التقرير', 'View Submissions': 'عرض التسليمات',
  'No results yet': 'لا توجد نتائج بعد', 'Partially released': 'منشورة جزئياً',
  'Release Results': 'نشر النتائج', 'Release results?': 'هل تريد نشر النتائج؟',
  'candidate results will become available according to this exam’s result visibility settings.': 'نتائج مرشحين ستصبح متاحة وفق إعدادات إظهار نتائج هذا الاختبار.',
  'Once released, candidates with portal access may be able to view their results.': 'بعد النشر، قد يتمكن المرشحون الذين لديهم دخول إلى البوابة من عرض نتائجهم.',
  'Results released successfully.': 'تم نشر النتائج بنجاح.',
  'Results can only be released when this exam’s visibility settings allow it.': 'يمكن نشر النتائج فقط عندما تسمح إعدادات إظهار نتائج هذا الاختبار بذلك.',
  'Preparing download…': 'جارٍ تجهيز التنزيل…', 'CSV': 'CSV', 'PDF': 'PDF', 'Word': 'Word',
  'Submissions': 'التسليمات', 'Results': 'النتائج', 'Reports': 'التقارير',
  'Candidates': 'المرشحون', 'Not started': 'لم يبدأ', 'In progress': 'قيد التقدم',
  'Submitted': 'تم التسليم', 'Auto-submitted': 'تم التسليم تلقائياً', 'Not submitted': 'لم يتم التسليم',
  'Cancelled': 'ملغى', 'Results available': 'النتائج المتاحة', 'Average %': 'متوسط النسبة المئوية',
  'Pass rate %': 'نسبة النجاح', 'Highest %': 'أعلى نسبة', 'Lowest %': 'أدنى نسبة',
  'Score': 'الدرجة', 'Total': 'المجموع', 'Percentage': 'النسبة المئوية', 'Grade': 'التقدير',
  'Pass / Fail': 'ناجح / راسب', 'Pass': 'ناجح', 'Fail': 'راسب', 'Passed': 'ناجح', 'Failed': 'راسب',
  'Candidate results': 'نتائج المرشحين', 'Released': 'منشورة', 'Not released': 'غير منشورة',
  'Release result': 'نشر النتيجة', 'Release this result to the candidate?': 'هل تريد نشر هذه النتيجة للمرشح؟',
  'View submission': 'عرض التسليم', 'View result': 'عرض النتيجة', 'Candidate response': 'إجابة المرشح',
  'Correct': 'صحيح', 'Incorrect': 'غير صحيح', 'Not marked': 'لم يتم التصحيح', 'Invalid': 'غير صالح',
  'Started': 'بدأ', 'Submitted at': 'وقت التسليم', 'Time used': 'الوقت المستغرق', 'seconds': 'ثوانٍ',
  'Search candidates': 'البحث عن المرشحين', 'Filter results': 'تصفية النتائج', 'Sort results': 'ترتيب النتائج',
  'Name': 'الاسم', 'Submission time': 'وقت التسليم', 'Highest percentage first': 'أعلى نسبة أولاً',
  'Highest score first': 'أعلى درجة أولاً', 'Latest submission first': 'أحدث تسليم أولاً',
  'No candidates have been added to this exam yet.': 'لم تتم إضافة مرشحين إلى هذا الاختبار بعد.',
  'Go to Candidates': 'الانتقال إلى المرشحين', 'No submissions yet.': 'لا توجد تسليمات بعد.',
  'Results will appear here after submissions are marked.': 'ستظهر النتائج هنا بعد تصحيح التسليمات.',
  'No candidates match these filters.': 'لا يوجد مرشحون مطابقون لهذه المرشحات.',
  'Only available results contribute to performance statistics.': 'تحتسب إحصاءات الأداء من النتائج المتاحة فقط.',
  'Results Export — CSV': 'تصدير النتائج — CSV', 'Client Result Report — PDF': 'تقرير نتائج العميل — PDF',
  'Editable Result Report — DOCX': 'تقرير نتائج قابل للتحرير — DOCX',
  'Reports include all participants and the latest submission for each candidate.': 'تشمل التقارير جميع المشاركين وآخر تسليم لكل مرشح.',
  'Download failed. Please try again.': 'تعذر التنزيل. يرجى المحاولة مرة أخرى.',
  'Refresh': 'تحديث', 'My results': 'نتائجي', 'No released results yet.': 'لا توجد نتائج منشورة بعد.',
  'Only your released results are shown.': 'تُعرض نتائجك المنشورة فقط.', 'Date': 'التاريخ',
  'Search exams': 'البحث عن الاختبارات', 'Specific-candidate delivery is not implemented.': 'لم يتم تنفيذ تسليم الاختبار لمرشحين محددين بعد.',
}
export const submissionLabels = { not_started: 'Not started', in_progress: 'In progress', submitted: 'Submitted', auto_submitted: 'Auto-submitted', not_submitted: 'Not submitted', cancelled: 'Cancelled' }
