export const setupCopy = {
  'Search attached questions': 'البحث في الأسئلة المرفقة',
  'Select question': 'تحديد السؤال',
  'Select all matching': 'تحديد جميع الأسئلة المطابقة',
  'Remove selected questions': 'إزالة الأسئلة المحددة',
  'Confirm removal': 'تأكيد الإزالة',
  'All matching attached questions across all pages are selected.': 'تم تحديد جميع الأسئلة المرفقة المطابقة عبر جميع الصفحات.',
  'No matching attached questions. Clear the search to see all attached questions.': 'لا توجد أسئلة مرفقة مطابقة. امسح البحث لرؤية جميع الأسئلة المرفقة.',
  'Remove these questions from this exam only? They will remain in the Question Bank.': 'هل تريد إزالة هذه الأسئلة من هذا الاختبار فقط؟ ستبقى في بنك الأسئلة.',
  'Remove this question from this exam only? It will remain in the Question Bank.': 'هل تريد إزالة هذا السؤال من هذا الاختبار فقط؟ سيبقى في بنك الأسئلة.',
  'Quick Exam candidates do not need platform accounts.': 'لا يحتاج مرشحو الاختبار السريع إلى حسابات على المنصة.',
  'Delivery method is fixed when the exam is created.': 'تثبت طريقة الدخول عند إنشاء الاختبار.',
  'Save the Exam Code before generating credentials.': 'احفظ رمز الاختبار قبل إنشاء بيانات الدخول.',
  'Assign': 'تعيين', 'Assign selected candidates': 'تعيين المرشحين المحددين', 'candidates selected': 'مرشحون محددون',
  'Active candidates only': 'المرشحون النشطون فقط',
  'All matching available candidates across all pages are selected. Clear selection to choose individual candidates.': 'تم تحديد جميع المرشحين المتاحين المطابقين عبر كل الصفحات. امسح التحديد لاختيار مرشحين منفردين.',
  'Through their account': 'من خلال حسابهم', 'Candidates sign in using their platform account.': 'يسجل المرشحون الدخول باستخدام حسابهم على المنصة.',
  'Candidates use Exam Code + Candidate ID + PIN.': 'يستخدم المرشحون رمز الاختبار ومعرف المرشح ورمز الدخول.',
  'Quick Exam currently supports Specific Candidates. Choose that eligibility in Candidates first.': 'يدعم الاختبار السريع حاليًا المرشحين المحددين. اختر هذه الأهلية في قسم المرشحين أولًا.',
  'Delivery is fixed once Quick access is configured.': 'تثبت طريقة الدخول بعد إعداد الدخول السريع.',
  'specific candidates assigned': 'مرشحون محددون معيّنون', 'group candidates eligible': 'مرشحو المجموعة المؤهلون',
  'Quick Exam access': 'دخول الاختبار السريع', 'Exam Code': 'رمز الاختبار',
  'Save Quick configuration to switch delivery. Assignments are retained.': 'احفظ إعداد الدخول السريع لتغيير طريقة الدخول. تبقى تعيينات المرشحين محفوظة.',
  'Generate credentials': 'إنشاء بيانات الدخول', 'Generate credentials for': 'إنشاء بيانات الدخول لعدد',
  'candidates assigned': 'مرشحون معيّنون', 'credentials generated': 'بيانات دخول منشأة', 'candidates need credentials': 'مرشحون يحتاجون إلى بيانات دخول',
  'existing credentials need an explicit Reset PIN.': 'بيانات دخول حالية تحتاج إلى إعادة تعيين رمز الدخول بشكل صريح.',
  'Save this sheet now. PINs cannot be downloaded again after leaving this page.': 'احفظ هذه الورقة الآن. لا يمكن تنزيل رموز الدخول مرة أخرى بعد مغادرة هذه الصفحة.',
  'Download credential sheet': 'تنزيل ورقة بيانات الدخول', 'Dismiss credential sheet': 'إغلاق ورقة بيانات الدخول',
  'Download did not start. Use Download credential sheet to save the generated PINs.': 'لم يبدأ التنزيل. استخدم تنزيل ورقة بيانات الدخول لحفظ رموز الدخول المنشأة.',
  'Select all': 'تحديد الكل', 'Clear selection': 'مسح التحديد', 'questions selected': 'أسئلة محددة', 'Add': 'إضافة',
  'All matching available questions across all pages are selected. Clear selection to choose individual questions.': 'تم تحديد جميع الأسئلة المتاحة المطابقة عبر كل الصفحات. امسح التحديد لاختيار أسئلة منفردة.',
  'No matching items found. Clear the search to see all available items.': 'لا توجد نتائج مطابقة. امسح البحث لعرض جميع العناصر المتاحة.',
  'Group / Cohort: Assign a group before saving group eligibility.': 'المجموعة: عيّن مجموعة قبل حفظ أهلية المجموعة.',
  'candidate_access: Remove direct candidate assignments before changing eligibility strategy.': 'أزل تعيينات المرشحين المباشرة قبل تغيير استراتيجية الأهلية.',
  'Questions: Select approved questions from the exam subject and workspace.': 'اختر أسئلة معتمدة من مادة الاختبار ومساحة العمل.',
  'Choose Specific Candidates before adding candidates.': 'اختر مرشحين محددين قبل إضافة المرشحين.',
  'Exam setup is frozen after participation starts.': 'لا يمكن تغيير إعداد الاختبار بعد بدء المشاركة.',
  'Add Questions': 'إضافة أسئلة', 'Add Candidates': 'إضافة مرشحين',
  'Specific Candidates': 'مرشحون محددون', 'Candidate eligibility': 'أهلية المرشحين',
  'Who should take this exam?': 'من يجب أن يؤدي هذا الاختبار؟',
  'Search questions': 'البحث عن أسئلة', 'Search by Candidate ID or name': 'البحث بمعرّف المرشح أو اسمه',
  'Already attached': 'مضاف بالفعل', 'Already assigned': 'معيّن بالفعل',
  'Add selected questions': 'إضافة الأسئلة المحددة', 'Add selected candidates': 'إضافة المرشحين المحددين',
  'No approved questions are available for this subject.': 'لا توجد أسئلة معتمدة متاحة لهذه المادة.',
  'Questions must be approved before they can be added to an exam.': 'يجب اعتماد الأسئلة قبل إضافتها إلى اختبار.',
  'Go to Question Bank': 'الانتقال إلى بنك الأسئلة', 'No candidates found.': 'لم يتم العثور على مرشحين.',
  'View question': 'عرض السؤال', 'Remove candidate': 'إزالة المرشح',
  'This candidate has participated and cannot be removed from the exam.': 'شارك هذا المرشح في الاختبار ولا يمكن إزالته منه.',
  'Quick Exam candidates are managed through credentials in Access.': 'تُدار بيانات دخول مرشحي الاختبار السريع في قسم الدخول.',
  'No group assigned': 'لم يتم تعيين مجموعة', 'Select group': 'اختر مجموعة', 'Save eligibility': 'حفظ الأهلية',
  'Only directly assigned active candidates are eligible.': 'المرشحون النشطون المعيّنون مباشرة فقط مؤهلون.',
  'No candidates assigned': 'لم يتم تعيين مرشحين', 'candidates': 'مرشحون', 'questions': 'أسئلة',
  'Remove this candidate from the exam?': 'هل تريد إزالة هذا المرشح من الاختبار؟',
  'Exam setup': 'إعداد الاختبار', 'Configuration': 'الإعدادات', 'No questions added': 'لم تتم إضافة أسئلة',
  'Candidate access configured': 'تم إعداد دخول المرشحين', 'No access method configured': 'لم يتم إعداد طريقة الدخول',
  'Assign a group before scheduling this exam.': 'عيّن مجموعة قبل جدولة هذا الاختبار.',
  'Schedule configured': 'تم إعداد الجدول', 'No schedule': 'لا يوجد جدول',
  'Candidate readiness could not be loaded.': 'تعذّر تحميل جاهزية المرشحين.',
  'Manage Questions': 'إدارة الأسئلة', 'Manage Candidates': 'إدارة المرشحين', 'Review Access': 'مراجعة الدخول',
  'Remove attached questions before changing the subject.': 'أزل الأسئلة المضافة قبل تغيير المادة.',
  'Create the draft, then manage questions and candidates in the exam workspace.': 'أنشئ المسودة، ثم أدر الأسئلة والمرشحين في مساحة الاختبار.',
  'Candidate Portal': 'بوابة المرشحين', 'How will candidates enter this exam?': 'كيف سيدخل المرشحون إلى هذا الاختبار؟',
  'Candidates sign in to their account to access eligible exams.': 'يسجّل المرشحون الدخول إلى حساباتهم للوصول إلى الاختبارات المؤهلين لها.',
  'Quick Exam uses Exam Code + Candidate ID + PIN. Remove direct assignments before changing delivery.': 'يستخدم الاختبار السريع رمز الاختبار ومعرّف المرشح ورمز الدخول. أزل التعيينات المباشرة قبل تغيير طريقة الدخول.',
  'Use Quick Exam': 'استخدام الاختبار السريع', 'Candidates enter with Exam Code + Candidate ID + PIN.': 'يدخل المرشحون باستخدام رمز الاختبار ومعرّف المرشح ورمز الدخول.',
  'Use Candidate Portal': 'استخدام بوابة المرشحين',
  'Quick Exam credentials': 'بيانات دخول الاختبار السريع',
}
