# Generated by Django 5.2.5 on 2026-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_active_group_membership',
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('candidate', 'group'), name='unique_candidate_group_membership'),
        ),
    ]
