# Generated by Django 5.2.17 on 2026-09-29 22:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_assessment_resume_allowed'),
        ('candidates', '0001_initial'),
        ('institutions', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='in_progress', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='candidates.candidate')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='institutions.institution')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_answers', to='questions.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.attempt')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('marked_for_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_questions', to='attempts.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_links', to='questions.question')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AttemptQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('attempt_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_options', to='attempts.attemptquestion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_orders', to='questions.questionoption')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='AnswerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='attempts.answer')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_selections', to='questions.questionoption')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('answer', 'option'), name='unique_option_per_answer')],
            },
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['institution', 'status'], name='attempt_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['candidate', 'assessment', 'status'], name='attempt_candidate_assess_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['expires_at', 'status'], name='attempt_expiry_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('candidate', 'assessment', 'attempt_number'), name='unique_candidate_assessment_attempt_no'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'question'], name='answer_attempt_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_question_per_attempt'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestion',
            constraint=models.UniqueConstraint(fields=('attempt', 'order'), name='unique_attempt_question_order'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestionoption',
            constraint=models.UniqueConstraint(fields=('attempt_question', 'option'), name='unique_option_per_attempt_question'),
        ),
        migrations.AddConstraint(
            model_name='attemptquestionoption',
            constraint=models.UniqueConstraint(fields=('attempt_question', 'order'), name='unique_attempt_option_order'),
        ),
    ]
